# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.ciphertext import Ciphertext


class Decision(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Decision - a model defined in OpenAPI

        ciphertext: The ciphertext of this Decision.
        decision: The decision of this Decision.
    """

    ciphertext: Ciphertext = Field(alias="ciphertext")
    decision: int = Field(alias="decision")

Decision.update_forward_refs()
