# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DecryptionOracleRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DecryptionOracleRequest - a model defined in OpenAPI

        ciphertext: The ciphertext of this DecryptionOracleRequest.
        iv: The iv of this DecryptionOracleRequest.
    """

    ciphertext: str = Field(alias="ciphertext")
    iv: str = Field(alias="iv")

DecryptionOracleRequest.update_forward_refs()
